LiveSmart/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^resolutions/', include('Resolutions.urls')),
]

Resolutions/urls.py
from django.conf.urls import url
from . import views

app_name='Resolutions'


urlpatterns = [
	# /resolutions/
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
	url(r'^(?P<resolution_id>[0-9]+)/$', views.detail, name='detail'),
    #url(r'^create_resolution/$', views.create_resolution, name='create_resolution'),
    #url(r'resolution/(?P<pk>[0-9]+)/$', views.ResolutionUpdate.as_view(), name='resolution-update'),
    url(r'(?P<resolution_id>[0-9]+)/delete_resolution/$', views.delete_resolution, name='delete_resolution'),
]

	

Resolutions/models.py
from django.contrib.auth.models import Permission, User
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.
class Resolution(models.Model):
	user = models.ForeignKey(User, default= 1)
	resolutionTitle = models.CharField(max_length = 50)

	def __str__(self):
		return self.resolutionTitle

class resolDescription(models.Model):
	resolution = models.ForeignKey(Resolution, on_delete=models.CASCADE) 
	resolutionDescription = models.CharField(max_length = 300)

	def __str__(self):
		return self.resolutionDescription

Resolutions/forms.py
from django.contrib.auth.models import User
from django import forms
from django.forms.extras.widgets import SelectDateWidget
import datetime
from .models import Resolution, resolDescription


class ResolutionForm(forms.ModelForm):

    class Meta:
        model = Resolution
        fields = ['resolutionTitle']

class DescriptionForm(forms.ModelForm):

    class Meta:
        model = resolDescription
        fields = ['resolutionDescription']




class UserForm(forms.ModelForm):
	username = forms.CharField(max_length=30, required=True, help_text='Optional.')
	firstName = forms.CharField(max_length=30, required=False, help_text='Optional.')
	surName = forms.CharField(max_length=30, required=False, help_text='Optional.')
	password = forms.CharField(widget=forms.PasswordInput)
	email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')
	dob = forms.DateField(label=('dob'), widget=SelectDateWidget(years=range(2018,1900,-1)))

	class Meta:
		model = User
		fields = ['username','firstName', 'surName','email', 'dob', 'password']

Resolutions/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render, get_object_or_404
from django.views.generic import View
from django.db.models import Q
from .models import Resolution, resolDescription
from .forms import UserForm, ResolutionForm


def index(request):
    if not request.user.is_authenticated():
        return render(request, 'Resolutions/login.html')
    else:
        resolutions = Resolution.objects.filter(user=request.user)
        description_results = resolDescription.objects.all()
        query = request.GET.get('q')
        if query:
            resolutions = resolutions.filter(
                Q(resolution_title__icontains=query)
                ).distinct()
            description_results = description_results.filter(
                Q(description_results__icontains=query)
                ).distinct()
            return render(request, 'Resolutions/index.html', {
                'resolutions': resolution,
                'description_results': description_results

            })
        else:
            return render(request, 'Resolutions/index.html', {'resolutions': resolutions})

'''def create_resolution(request):
    if not request.user.is_authenticated():
        return render(request, 'Resolutions/login.html')
    else:
        form = ResolutionForm(request.POST or None)
        if form.is_valid():
            resolution = form.save(commit=False)
            resolution.user = request.user
            resolution.resolutionTitle = resolution.cleaned_data['resolutionTitle']
            resolution.save()
            return render(request, 'Resolutions/detail.html', {'resolution': resolution})
        context = {
            'form': form,
        }
        return render(request, 'Resolutions/create_resolution.html', context)
'''
def delete_resolution(request, resolution_id):
    resolution = Resolution.objects.get(pk=resolution_id)
    resolution.delete()
    resolution = Resolution.objects.filter(user=request.user)
    return render(request, 'Resolutions/index.html', {'resolution': resolution})

def detail(request, resolution_id):
    if not request.user.is_authenticated():
        return render(request, 'Resolutions/login.html')
    else:
        user = request.user
        resolution = get_object_or_404(Resolution, pk=resolution_id)
        return render(request, 'Resolutions/detail.html', {'resolution': resolution, 'user': user})

def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'Resolutions/login.html', context)

def login_user(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                resolutions = Resolution.objects.filter(user=request.user)
                return render(request, 'resolutions/index.html', {'resolutions': resolutions})
            else:
                return render(request, 'resolutions/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'resolutions/login.html', {'error_message': 'Invalid login'})
    return render(request, 'resolutions/login.html')



def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        firstName = form.cleaned_data['firstName']
        surName = form.cleaned_data['surName']
        email = form.cleaned_data['email']
        dob = form.cleaned_data['dob']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=email, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                resolution = Resolution.objects.filter(user=request.user)
                return render(request, 'Resolutions/index.html', {'resolutions': resolutions})
    context = {
        "form": form,
    }
    return render(request, 'Resolutions/register.html', context)

Resolutions/templates/Resolutions/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8" />
	<title>{% block title %}New Year's resolutions{% endblock %}</title>
	{% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css" href="{% static 'Resolutions/style.css' %}" />
</head>
<body>

<nav class="navbar navbar-inverse">
	<div class="container-fluid">
	<!--Header-->
		<div class="navbar-header">
		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</button>
			<a class="navbar-brand" href="{% url 'Resolutions:index' %} ">New Year's resolutions</a>
		</div>
	<!--Items-->
	<div class="collapse navbar-collapse" id="topNavBar">
		<ul class="nav navbar-nav">
			<li class="{% block albums_active %}{% endblock %}">
				<a href="{% url 'Resolutions:index' %}" >Resolutions Title</a>
			</li>
			<li class="">
				<a href="#" >Resolutions Description</a>
			</li>
		</ul>

		<form class="navbar-form navbar-left" role="search" method="get" action="#">
			<div class="form-group">
				<input type="text" class="form-control" name="q" value="">
			</div>
			<button type="submit" class="btn btn-default">Search</button>
		</form>
		
		<ul class="nav navbar-nav navbar-right">
			<li class="">
				<a href="{% url 'Resolutions: create_resolution' %}" >
					<span class="glyphicon glyphicon-plus" aria-hidden="true">&nbsp;Add Resolution</span>
				</a>
			</li>
			<li class="">
				 <a href="{% url 'Resolutions : logout_user' %}" >
					<span class="glyphicon glyphicon-off" aria-hidden="true">&nbsp;Log out</span>
				</a>
			</li>
		</ul>

	</div>
</nav>

{% block body %}

{% endblock %}
</body>
</html>

Resolutions/templates/Resolutions/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}New Year's resolutions{% endblock %}</title>
    {% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css" href="{% static 'Resolutions/style.css' %}" />
  
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

      
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'Resolutions:index' %}">Resolutions</a>
        </div>

       
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block register_active %}{% endblock %}"><a href="{% url 'Resolutions:register' %}">Register</a></li>
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'Resolutions:login_user' %}">Log In</a></li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

Resolutions/templates/Resolutions/create_resolution.html
{% extends 'Resolutions/base.html' %}
{% block title %}Add a New Resolution{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add a New Resolution</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'Resolutions/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}

Resolutions/templates/Resolutions/detail.html
{% extends 'Resolutions/base.html' %}
{% block title %} Resolution description{% endblock %}

{% block body %}


	<h3 class="text-center">{{resolution.resolutionTitle}} Description</h3>
	{% if error_message %}
		<p><strong>{{error_message}}</strong></p>
	{% endif %}
	<div class="container">
    	<ul class="list-group">	
		{% for description in resolution.resoldescription_set.all  %}
			<li class="list-group-item clearfix">
				{{description}}
					<span class="pull-right button-group">
                		<a href="#" class="btn btn-primary"><span class="glyphicon glyphicon-edit"></span> Edit</a> 
                		<button type="button" class="btn btn-danger"><span class="glyphicon glyphicon-remove"></span> Delete</button>
            		</span>
			</li>
		
		{% endfor %}	
		</ul>
	</div>
{% endblock %}

Resolutions/templates/Resolutions/form-template.html
{%  for field in form %}
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<span class="text-danger small">{{ field.errors }}</span>
		</div>
		<label class="control-label col-sm-2">{{ field.label_tag }}</label>
		<div class="col-sm-10">{{ field }}</div>	
	</div>	
{% endfor %}	

Resolutions/templates/Resolutions/index.html
{% extends 'Resolutions/base.html' %}
{% block albums_active %}active{% endblock %}

	{% block body %}

	<div class="row">
        <div class="col-sm-12 text-center">
            <h3>Here are all your New Year's resolutions:{{ user.username }}'s Albums</h3>
        </div>
	{% if resolutions %}
			<div class="container">
				<ul class="list-group">
				{% for resolution in resolutions %}
					<li class="list-group-item clearfix">
						<a href="{% url 'Resolutions:index' %}">{{ resolution.resolutionTitle }}</a>
							<span class="pull-right button-group">
               					 
								<form action="{% url "Resolutions:resolution-delete" resolution.id %}" method="post" style="display: inline;">
									{% csrf_token %}
									<input type="hidden" name="resolution_id" value="{{resolution.id}}" />
								    <button type="submit"  class="btn btn-danger"><span class="glyphicon glyphicon-remove"></span> Delete</button> 	
								</form>
               					
            				</span>
					</li>
				{% endfor %}
			</ul>
	{% else %}
		<h3 class="col-sm-12 text-center">You don't have any resolutions</h3>
	{% endif %}
{% endblock %}

Resolutions/templates/Resolutions/login.html
{% extends 'Resolutions/base_visitor.html' %}
{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'Resolutions:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'Resolutions:register' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

Resolutions/templates/Resolutions/register.html
{% extends 'Resolutions/base_visitor.html' %}
{% block title %}Register{% endblock %}
{% block register_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Register for an Account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'resolutions/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Already have an account? <a href="{% url 'Resolutions:login_user' %}">Click here</a> to log in.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

Resolutions/templates/Resolutions/registration_form.html
{% extends 'Resolutions/base.html' %}
{% block title %} Register{% endblock %}

{% block body %}
	<div class="container-fluid">
		<div class="col-sm-12 com-md-7">
			<div class="panel panel-default">
				<div class="panel-body">
				<h3>Create a new account</h3>
					<form class="form-horizontal" action="" method="post">
						{% csrf_token %}
						{% include 'Resolutions/form-template.html' %}
						<div class="form-group">
							<div class="col-sm-offset-2 col-sm-10">
								<button type="submit" class="btn btn-success">Submit</button>
							</div>
						</div>
					</form>
				</div>
			</div> 
		</div>
	</div>
{% endblock %}

Resolutions/templates/Resolutions/resolution_form.html
{% extends 'Resolutions/base.html' %}
{% block title %} Resolution description{% endblock %}

{% block body %}
	<div class="container-fluid">
		<div class="col-sm-12 com-md-7">
			<div class="panel panel-default">
				<div class="panel-body">
					<form class="form-horizontal" action="" method="post">
						{% csrf_token %}
						{% include 'Resolutions/form-template.html' %}
						<div class="form-group">
							<div class="col-sm-offset-2 col-sm-10">
								<button type="submit" class="btn btn-success">Submit</button>
							</div>
						</div>
					</form>
				</div>
			</div> 
		</div>
	</div>
{% endblock %}